name: Pages
on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install yarn
        run: npm i --global yarn

      - name: Install deps
        run: yarn

      - name: Build
        run: PUBLIC_PATH=/vh-widget/ yarn run build

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pages

